version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
   
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
